// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: test/test.proto

package test

import (
	"github.com/infobloxopen/atlas-app-toolkit/query"
	//fmt "fmt"
	//proto "github.com/gogo/protobuf/proto"
	_ "github.com/infobloxopen/atlas-app-toolkit/query"
	"github.com/infobloxopen/protoc-gen-atlas-query-validate/options"
	_ "github.com/infobloxopen/protoc-gen-atlas-query-validate/options"
	//math "math"
)

// Reference imports to suppress errors if they are not otherwise used.

var TestMethodsRequireFilteringValidation = map[string]map[string]options.FilteringOption{
	"/test.TestService/List": map[string]options.FilteringOption{
		"subject": options.FilteringOption{ValueType: options.QueryValidate_STRING},
		"name":    options.FilteringOption{Deny: []options.QueryValidate_FilterOperator{options.QueryValidate_MATCH}, ValueType: options.QueryValidate_STRING},
	},
}
var TestMethodsRequireSortingValidation = map[string][]string{
	"/test.TestService/List": []string{
		"name",
	},
}
var TestMethodsRequireFieldSelectionValidation = map[string][]string{}

func TestValidateFiltering(methodName string, f *query.Filtering) error {
	info, ok := TestMethodsRequireFilteringValidation[methodName]
	if !ok {
		return nil
	}
	return options.ValidateFiltering(f, info)
}
func TestValidateSorting(methodName string, s *query.Sorting) error {
	info, ok := TestMethodsRequireSortingValidation[methodName]
	if !ok {
		return nil
	}
	return options.ValidateSorting(s, info)
}
func TestValidateFieldSelection(methodName string, s *query.FieldSelection) error {
	info, ok := TestMethodsRequireFieldSelectionValidation[methodName]
	if !ok {
		return nil
	}
	return options.ValidateFieldSelection(s, info)
}
